arrowParens: 'avoid'
bracketSpacing: true
jsxSingleQuote: false
printWidth: 120
semi: true
singleQuote: true
tabWidth: 2
trailingComma: 'all'
overrides:
  - files:
      - '*.tsx'
      - '*.ts'
    options:
      tabWidth: 4
